project_id = "eeqfqklcdstbziedsnxc"

[functions.create-practice-during-setup]
verify_jwt = true

[functions.step-help-chat]
verify_jwt = true

[functions.create-user-accounts]
verify_jwt = true

[functions.create-master-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.suggest-improvements]
verify_jwt = true

[functions.policy-review-reminders]
verify_jwt = false

[functions.generate-scripts-claim-pdf]
verify_jwt = true

[functions.generate-test-data]
verify_jwt = false

[functions.create-initial-processes]
verify_jwt = true

[functions.create-missing-accounts]
verify_jwt = true

[functions.send-policy-review-emails]
verify_jwt = false

[functions.send-policy-acknowledgment-reminders]
verify_jwt = false

[functions.send-policy-escalation-emails]
verify_jwt = false

[functions.resend-webhook-handler]
verify_jwt = false