project_id = "eeqfqklcdstbziedsnxc"

[functions.step-help-chat]
verify_jwt = true

[functions.create-user-accounts]
verify_jwt = true

[functions.create-master-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true